### ISSUE TITLE
Installing via nuget

### ISSUE THREAD

**Issue by tadeuszwojcik** [EgorBo/SimdJsonSharp#8]
Hi,
I wanted to try out this awesome piece of code, but not 100% why nuget installation fails with following message:
```
Detected package downgrade: Microsoft.NETCore.Platforms from 3.0.0-preview3.19115.9 to 3.0.0-preview.19073.11. Reference the package directly from the project to select a different version. 
 OriginClient -> SimdJsonSharp 1.0.3 -> Microsoft.NETCore.Platforms (>= 3.0.0-preview3.19115.9) 
 OriginClient -> Microsoft.NETCore.Platforms (>= 3.0.0-preview.19073.11)
Package restore failed. Rolling back package changes for 'OriginClient'.
```
I've got  .NET Core 3.0.0-preview2 installed on my machine, it's not yet compatible with it?
Thanks!

**Comment by Tornhoof** [comment]
You need a more recent version of the previews. 
Check https://github.com/dotnet/core-sdk for the most recent ones.

**Comment by tadeuszwojcik** [comment]
Thanks!
