### ISSUE TITLE
Consider updating to simdjson 0.1.1

### ISSUE THREAD

**Issue by lemire** [EgorBo/SimdJsonSharp#9]
We have a new version which has precomputed string lengths, and supporting strings with null characters in them.

**Comment by EgorBo** [comment]
@lemire um.. I see the PR is merged but singleheader sources are out of date, maybe they should not be under source control at all or there should be a CI bot that will update them after each commit, something like that?

**Comment by lemire** [comment]
They surely got updated... https://github.com/lemire/simdjson/tree/master/singleheader

Let me check.

**Comment by lemire** [comment]
Ok. Go with 0.1.1. Something went out of order during the release so in 0.1.0, the singleheader version did not get updated quite right.

**Comment by EgorBo** [comment]
Updated SimdJsonSharp.Bindings to be in sync with 0.1.1 (bindings for get_string_length were added earlier - I basically cherry-picked your PR before you merge it - I couldn't wait to optimize my utf16 strings 😄).

Will update SimdJsonSharp.Managed version later (working on a small automatic C++-to-C# translator)

**Comment by lemire** [comment]
I am hoping that for select JSON files, you’ll see perf. benefits.
